import type { Metadata } from 'next';
import './globals.css';
import ReduxToolkitProvider from '@/config/ReduxProvider';
import Nav from '@/components/Nav';

export const metadata: Metadata = {
  title: 'Ask for...',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReduxToolkitProvider>
        <body className='bg-defaultMint'>
          <div className='bg-white border-2 border-solid border-defaultGreen p-2 w-1/2 mx-auto my-12 relative'>
            <Nav />
            <div>{children}</div>
          </div>
        </body>
      </ReduxToolkitProvider>
    </html>
  );
}
