import type { Metadata } from 'next';
import './globals.css';
import ReduxToolkitProvider from '@/config/ReduxProvider';
import Nav from '@/components/Nav';

export const metadata: Metadata = {
  title: 'Ask for...',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReduxToolkitProvider>
        <body>
          <Nav />
          <div>{children}</div>
        </body>
      </ReduxToolkitProvider>
    </html>
  );
}
